config/routes.rb
Rails.application.routes.draw do
  root 'practice#input'

  get 'output' => 'practice#output'

  post 'output' => 'practice#output'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def input
  end

  def output
  	
  	@color = params[:color]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeParams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/practice/input.html.erb
<h1>Input Page</h1>

<p>
	<%= link_to "Red", output_path(color: "red") %>
</p>

<p>
	<%= link_to "Blue", output_path(color: "blue") %>
</p>

<p>
	<%= link_to "Green", output_path(color: "green") %>
</p>

<%= form_tag output_path, method: "post" do %>
	<p>
		<%= text_field_tag "color",nil,placeholder:"What color?" %>
	</p>
	<p>
		<%= submit_tag "Submit" %>
	</p>


<% end %>

app/views/practice/output.html.erb
<style>
	.box {
		background-color:<%= @color %>;
		width: 100px;
		height: 100px;
		color:white;
	}

</style>

<h1>Colors</h1>

<div class = "box">
	<%= @color %>
</div>